#listener {
#    timeout = 10                                 # 2.5 minutes
    #on-timeout = notify-send "You are idle!"      # optional notification
#}

listener {
    timeout = 600                                 # 5 minutes
    on-timeout = hyprlock                         # lock screen (requires hyprlock)
}

listener {
    timeout = 330                                 # 5.5 minutes
    on-timeout = hyprctl dispatch dpms off        # turn off screen
    on-resume = hyprctl dispatch dpms on          # turn on screen when activity resumes
}

